stages:
  - setup
  - vet
  - test
  - build
  - pages

image: node:12.22.1

cache:
  untracked: true
  key:
    files:
      - package-lock.json
  paths:
    - node_modules

before_script:
  - node --version
  - npm --version

setup:
  stage: setup
  script:
    - make setup

check:
  stage: vet
  script:
    - make vet:check

lint:
  stage: vet
  script:
    - make vet:lint

test:
  stage: test
  script:
    - make test

debug:
  stage: build
  script:
    - make build:debug

release:
  stage: build
  script:
    - make build:release

pages:
  stage: pages
  before_script:
  script:
    - make build:release
    - rm -fr public && mkdir -p public
    - cp -R dst/* public/
    - hash=$(md5sum public/js/script.min.js | cut -d ' ' -f 1)
    - mv public/js/script.min{,.$hash}.js
    - sed "s/\.js/\.min\.${hash}\0/" -i public/index.html
  artifacts:
    untracked: true
    paths:
      - public
